//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Resources;
using System.Runtime.CompilerServices;

namespace SimpleBinder.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("SimpleBinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wanna save binds before exit?.
        /// </summary>
        internal static string exitToolStripMenuItem_Click_Text {
            get {
                return ResourceManager.GetString("exitToolStripMenuItem_Click_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string exitToolStripMenuItem_Click_Warning {
            get {
                return ResourceManager.GetString("exitToolStripMenuItem_Click_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a Config(Json) File.
        /// </summary>
        internal static string exportToolStripMenuItem_Click {
            get {
                return ResourceManager.GetString("exportToolStripMenuItem_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Config(Json) File.
        /// </summary>
        internal static string importStripMenuItem_Text {
            get {
                return ResourceManager.GetString("importStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json config|*.json.
        /// </summary>
        internal static string importStripMenuItemClick_Json_config {
            get {
                return ResourceManager.GetString("importStripMenuItemClick_Json_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ParseFromJsonToWinForms_Error {
            get {
                return ResourceManager.GetString("ParseFromJsonToWinForms_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something gone wrong with parsing values from your config(.json).
        /// </summary>
        internal static string ParseFromJsonToWinForms_Error_Message {
            get {
                return ResourceManager.GetString("ParseFromJsonToWinForms_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wanna close binder?.
        /// </summary>
        internal static string SimpleBinder_Binder_FormClosing_Text {
            get {
                return ResourceManager.GetString("SimpleBinder_Binder_FormClosing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off.
        /// </summary>
        internal static string statusButton_Turn_Off {
            get {
                return ResourceManager.GetString("statusButton_Turn_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On.
        /// </summary>
        internal static string statusButton_Turn_On {
            get {
                return ResourceManager.GetString("statusButton_Turn_On", resourceCulture);
            }
        }
    }
}
